HEADER_TEMPLATE = """# agent-context.md
# AUTO-GENERATED by react-agent-bridge Discovery Mode
# Last updated: {timestamp}
# Sessions analysed: {session_count} ({human_count} human, {agent_count} agent)
# Application version: {version_hash}
#
# HOW TO USE THIS FILE:
# - Sections marked [REVIEW NEEDED] require developer attention
# - INFERRED constraints are not enforced until promoted to CONFIRMED
# - Sensitive Context section must be filled in manually
# - Re-run discovery mode to update inferred content as the app evolves

"""

GLOSSARY_HEADER = """## Component Glossary
# {session_count} sessions | Last updated: {timestamp}

"""

COMPONENT_TEMPLATE = """### {component_name}
# Route: {routes}
# Observed: {session_count} sessions
"""

SLOT_TEMPLATE = """#### {slot_key}
# Type: {inferred_type} | Sensitive: {sensitive} | Derived: {derived} | Volatile: {volatile}
# Confidence: {confidence:.2f}
# {review_marker}Description: {description}
# Observed values: {examples}
"""

WORKFLOWS_HEADER = """## Workflow Definitions
# {workflow_count} workflows identified

"""

WORKFLOW_TEMPLATE = """### {workflow_name}
# Confidence: {confidence:.2f} | Sessions: {session_count} | Avg steps: {avg_step_count}

Preconditions:
{preconditions}

Steps:
{steps}

Success condition: {success_condition}
Failure condition: {failure_condition}
"""

CONSTRAINTS_HEADER = """## Constraints
# {confirmed_count} confirmed | {inferred_count} awaiting review

"""

CONSTRAINT_TEMPLATE = """### {constraint_name}
# Status: {status}
# Type: {constraint_type}
# Confidence: {confidence:.2f} | Sessions: {session_count}
# Evidence: {evidence_summary}
{description}
"""

SENSITIVE_CONTEXT_TEMPLATE = """## Sensitive Context
# This section must be filled in manually.
# The runtime cannot observe sensitive business context from usage data.
# Examples of what belongs here:
# - Test environment signals (error codes that mean something different in staging)
# - Internal routes not visible in the UI
# - Business rules that cannot be inferred from state transitions
"""
