import os

def main():
    print("Resetting Discovery Mode Session Knowledge...")
    
    # 1. Delete discovery.db
    db_path = "discovery.db"
    if os.path.exists(db_path):
        try:
            os.remove(db_path)
            print(f"  Deleted {db_path}")
        except Exception as e:
            print(f"  Error deleting {db_path}: {e}")
            
    # 2. Reset agent-context.md to clean template
    context_path = "agent-context.md"
    template = """# agent-context.md
# AUTO-GENERATED by react-agent-bridge Discovery Mode
# Last updated: 2026-06-10 08:35:00
# Sessions analysed: 0 (0 human, 0 agent)
# Application version: initial_v1
#
# HOW TO USE THIS FILE:
# - Sections marked [REVIEW NEEDED] require developer attention
# - INFERRED constraints are not enforced until promoted to CONFIRMED
# - Sensitive Context section must be filled in manually
# - Re-run discovery mode to update inferred content as the app evolves

## Component Glossary
# 0 sessions | Last updated: 2026-06-10 08:35:00

## Workflow Definitions
# 0 workflows identified

## Constraints
# 0 confirmed | 0 awaiting review

## Sensitive Context
# This section must be filled in manually.
# The runtime cannot observe sensitive business context from usage data.
# Examples of what belongs here:
# - Test environment signals (error codes that mean something different in staging)
# - Internal routes not visible in the UI
# - Business rules that cannot be inferred from state transitions
"""
    try:
        with open(context_path, "w", encoding="utf-8") as f:
            f.write(template)
        print(f"  Reset {context_path}")
    except Exception as e:
        print(f"  Error resetting {context_path}: {e}")

    print("Reset complete!")

if __name__ == "__main__":
    main()
