import os
import time
import json
import pytest
import sqlite3
from unittest.mock import AsyncMock, MagicMock

from react_agent_bridge.discovery.event import DiscoveryEvent, DiscoveryEventType
from react_agent_bridge.discovery.corpus import ObservationCorpus
from react_agent_bridge.discovery.recorder import HumanSessionRecorder
from react_agent_bridge.discovery.analyzer.slot_annotator import SlotAnnotationEngine
from react_agent_bridge.discovery.analyzer.workflow import WorkflowInferenceEngine
from react_agent_bridge.discovery.analyzer.precondition import PreconditionInferenceEngine
from react_agent_bridge.discovery.analyzer.constraint import ConstraintInferenceEngine
from react_agent_bridge.discovery.generator.context_writer import ContextWriter


@pytest.fixture
def temp_db(tmp_path):
    db_file = tmp_path / "test_discovery.db"
    return str(db_file)


@pytest.mark.asyncio
async def test_sensitive_value_exclusion(temp_db):
    corpus = ObservationCorpus(temp_db)
    
    # Mock bridge
    mock_bridge = MagicMock()
    mock_bridge.graph = MagicMock()
    mock_bridge.graph.get_slot_value.return_value = ""
    
    recorder = HumanSessionRecorder(mock_bridge, corpus, session_type="human")
    await recorder.start()
    
    # Send sensitive slot state snapshot
    await recorder.on_message({
        "type": "stateSnapshot",
        "target": "AuthStore.password",
        "value": "super_secret_123"
    })
    
    # Query database directly to verify raw value was redacted
    conn = sqlite3.connect(temp_db)
    cursor = conn.cursor()
    cursor.execute("SELECT previous_value_json, new_value_json FROM events WHERE slot_key = 'password'")
    row = cursor.fetchone()
    conn.close()
    
    assert row is not None
    # Previous value was empty/None, new value should be [REDACTED]
    assert json.loads(row[1]) == "[REDACTED]"


@pytest.mark.asyncio
async def test_inferred_only_guarantee(temp_db):
    corpus = ObservationCorpus(temp_db)
    
    # Insert some synthetic events so ConstraintInferenceEngine runs
    now = time.time()
    for i in range(6):
        sid = f"session_{i}"
        await corpus.start_session(sid, "human", now, "version_hash_1")
        
        # Route mount event
        await corpus.record_event(DiscoveryEvent(
            event_type=DiscoveryEventType.COMPONENT_MOUNTED,
            timestamp=now + 0.1,
            session_id=sid,
            session_type="human",
            component_display_name="SecurityPanel",
            route="/home"
        ))
        
        # State slot change
        await corpus.record_event(DiscoveryEvent(
            event_type=DiscoveryEventType.SLOT_CHANGED,
            timestamp=now + 0.2,
            session_id=sid,
            session_type="human",
            component_display_name="SecurityPanel",
            slot_key="criticalAlertThreshold",
            previous_value=85,
            new_value=90,
            route="/home"
        ))
        
        await corpus.end_session(sid, now + 1.0, is_complete=True)

    # Run slot annotator first
    annotator = SlotAnnotationEngine(corpus)
    annotations = await annotator.analyze()
    
    # Run ConstraintInferenceEngine
    engine = ConstraintInferenceEngine(corpus, min_sessions=3)
    constraints = await engine.analyze(annotations)
    
    assert len(constraints) > 0
    for c in constraints:
        # Guarantee: Constraint status must strictly be INFERRED
        assert c["status"] == "INFERRED"
        assert c["status"] != "CONFIRMED"


@pytest.mark.asyncio
async def test_developer_edit_preservation(tmp_path):
    output_path = tmp_path / "agent-context.md"
    
    # Write initial agent-context.md with custom edits
    initial_content = """# agent-context.md
# AUTO-GENERATED by react-agent-bridge Discovery Mode

## Component Glossary
### SecurityPanel
# Route: ['/home']
# Observed: 1 sessions

#### criticalAlertThreshold
# Type: number | Sensitive: no | Derived: no | Volatile: no
# Confidence: 1.00
# Description: This description was customized by the developer manually!
# Observed values: 85, 90

## Constraints
# 1 confirmed | 0 awaiting review

### Scope_SecurityPanel
# Status: CONFIRMED
# Type: scope
# Confidence: 1.00 | Sessions: 5
# Evidence: Component SecurityPanel was only observed mounted on routes: ['/home'].
This is the custom description for the scope constraint.

## Sensitive Context
Developer manual notes go here.
Do not overwrite this!
"""
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(initial_content)
        
    writer = ContextWriter(str(output_path))
    
    # New inferred annotations, workflows, constraints
    annotations = {
        "SecurityPanel.criticalAlertThreshold": {
            "inferred_type": "number",
            "is_probably_sensitive": False,
            "is_derived": False,
            "is_volatile": False,
            "confidence": 1.0,
            "description_draft": "Tracks the criticalAlertThreshold state for SecurityPanel. Observed values: 85, 90",
            "observed_value_examples": ["85", "90"],
            "routes_observed_on": ["/home"]
        }
    }
    
    inferred_constraints = [
        {
            "name": "Scope_SecurityPanel",
            "status": "INFERRED",
            "constraint_type": "scope",
            "confidence": 1.0,
            "session_count": 5,
            "evidence_summary": "Component SecurityPanel was only observed mounted on routes: ['/home'].",
            "description": "Component SecurityPanel is scoped and should only be accessed on routes: ['/home']."
        }
    ]
    
    session_metrics = {"total": 5, "human": 5, "agent": 0}
    
    # Write back context file
    writer.write(
        annotations=annotations,
        workflows=[],
        inferred_constraints=inferred_constraints,
        session_metrics=session_metrics,
        version_hash="version_hash_1"
    )
    
    with open(output_path, "r", encoding="utf-8") as f:
        updated_content = f.read()
        
    # Assert custom edits are fully preserved
    assert "This description was customized by the developer manually!" in updated_content
    assert "# Status: CONFIRMED" in updated_content
    assert "This is the custom description for the scope constraint." in updated_content
    assert "Developer manual notes go here." in updated_content


@pytest.mark.asyncio
async def test_workflow_and_precondition_inference(temp_db):
    corpus = ObservationCorpus(temp_db)
    
    # Insert 5 successful sessions
    now = time.time()
    for i in range(5):
        sid = f"success_session_{i}"
        await corpus.start_session(sid, "human", now, "version_hash_1")
        
        # Terms Accepted state initially set
        await corpus.record_event(DiscoveryEvent(
            event_type=DiscoveryEventType.SLOT_CHANGED,
            timestamp=now + 0.05,
            session_id=sid,
            session_type="human",
            component_display_name="App",
            slot_key="termsAccepted",
            previous_value=False,
            new_value=True,
            route="/"
        ))

        # Step 1: Input username
        await corpus.record_event(DiscoveryEvent(
            event_type=DiscoveryEventType.SLOT_CHANGED,
            timestamp=now + 0.1,
            session_id=sid,
            session_type="human",
            component_display_name="App",
            slot_key="username",
            previous_value="",
            new_value="user_john",
            route="/"
        ))
        
        # Step 2: Input PIN
        await corpus.record_event(DiscoveryEvent(
            event_type=DiscoveryEventType.SLOT_CHANGED,
            timestamp=now + 0.2,
            session_id=sid,
            session_type="human",
            component_display_name="App",
            slot_key="pin",
            previous_value="",
            new_value="1234",
            route="/"
        ))
        
        # Terminal step: Login Success
        await corpus.record_event(DiscoveryEvent(
            event_type=DiscoveryEventType.SLOT_CHANGED,
            timestamp=now + 0.3,
            session_id=sid,
            session_type="human",
            component_display_name="App",
            slot_key="loginSuccess",
            previous_value=False,
            new_value=True,
            route="/"
        ))
        
        await corpus.end_session(sid, now + 1.0, is_complete=True)
        
    # Insert 3 stalled sessions (preceding step succeeded, but terminal did not because terms not accepted)
    for i in range(3):
        sid = f"stalled_session_{i}"
        await corpus.start_session(sid, "human", now, "version_hash_1")
        
        # termsAccepted is False or never set to True
        await corpus.record_event(DiscoveryEvent(
            event_type=DiscoveryEventType.SLOT_CHANGED,
            timestamp=now + 0.05,
            session_id=sid,
            session_type="human",
            component_display_name="App",
            slot_key="termsAccepted",
            previous_value=False,
            new_value=False,
            route="/"
        ))

        # Step 1: Input username (BUT NO PIN)
        await corpus.record_event(DiscoveryEvent(
            event_type=DiscoveryEventType.SLOT_CHANGED,
            timestamp=now + 0.1,
            session_id=sid,
            session_type="human",
            component_display_name="App",
            slot_key="username",
            previous_value="",
            new_value="stalled_user",
            route="/"
        ))
        
        await corpus.end_session(sid, now + 1.0, is_complete=True)

    # Run WorkflowInferenceEngine
    wf_engine = WorkflowInferenceEngine(corpus)
    workflows = await wf_engine.analyze(min_confidence=0.5)
    
    assert any(w["name"] == "App loginSuccess Workflow" for w in workflows)
    wf = [w for w in workflows if w["name"] == "App loginSuccess Workflow"][0]
    assert len(wf["steps"]) == 3
    assert wf["steps"][0]["target"] == "App.termsAccepted"
    assert wf["steps"][1]["target"] == "App.username"
    assert wf["steps"][2]["target"] == "App.pin"

    # Run PreconditionInferenceEngine
    pre_engine = PreconditionInferenceEngine(corpus, min_pairs=2, confidence_threshold=0.6)
    preconditions = await pre_engine.analyze_preconditions(workflows)
    
    assert wf["name"] in preconditions
    pre_list = preconditions[wf["name"]]
    assert len(pre_list) > 0
    assert pre_list[0]["slot_target"] == "App.termsAccepted"
    assert pre_list[0]["operator"] == "truthy"

